import {Cormorant_Unicase, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const cormorant_unicase = Cormorant_Unicase({ 
  subsets: ["latin"],
  weight:['300', '400', '500', '600', '700'], 
  variable:"--font-cormorant_unicase"

});

const open_sans = Open_Sans({ 
  subsets: ["latin"],
  weight:['300', '400', '500', '600', '700', '800'], 
  variable:"--font-open_sans"

});

export const metadata = {
  title: " Coffee Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cormorant_unicase.variable}, ${open_sans.variable}`}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
